FROM --platform=linux/amd64 node:19

ARG ARMAGEDDON_SEED_USER_PASS
ENV ARMAGEDDON_SEED_USER_PASS=${ARMAGEDDON_SEED_USER_PASS}

ARG ARMAGEDDON_SEED_GUEST_USER_PASS
ENV ARMAGEDDON_SEED_GUEST_USER_PASS=${ARMAGEDDON_SEED_GUEST_USER_PASS}

ARG ARMAGEDDON_ACCESS_TOKEN_SECRET
ENV ARMAGEDDON_ACCESS_TOKEN_SECRET=${ARMAGEDDON_ACCESS_TOKEN_SECRET}

ARG ARMAGEDDON_REFRESH_TOKEN_SECRET
ENV ARMAGEDDON_REFRESH_TOKEN_SECRET=${ARMAGEDDON_REFRESH_TOKEN_SECRET}

ARG ARMAGEDDON_ACCESS_TOKEN_ALGORITHM
ENV ARMAGEDDON_ACCESS_TOKEN_ALGORITHM=${ARMAGEDDON_ACCESS_TOKEN_ALGORITHM}

ARG ARMAGEDDON_REFRESH_TOKEN_ALGORITHM
ENV ARMAGEDDON_REFRESH_TOKEN_ALGORITHM=${ARMAGEDDON_REFRESH_TOKEN_ALGORITHM}

ARG ARMAGEDDON_ACCESS_TOKEN_EXPIRATION
ENV ARMAGEDDON_ACCESS_TOKEN_EXPIRATION=${ARMAGEDDON_ACCESS_TOKEN_EXPIRATION}

ARG ARMAGEDDON_REFRESH_TOKEN_EXPIRATION
ENV ARMAGEDDON_REFRESH_TOKEN_EXPIRATION=${ARMAGEDDON_REFRESH_TOKEN_EXPIRATION}

ARG ARMAGEDDON_RND_BYTES_SZ
ENV ARMAGEDDON_RND_BYTES_SZ=${ARMAGEDDON_RND_BYTES_SZ}

ARG ARMAGEDDON_DERIVED_KEY_LEN
ENV ARMAGEDDON_DERIVED_KEY_LEN=${ARMAGEDDON_DERIVED_KEY_LEN}

ARG ARMAGEDDON_NANOID_LEN
ENV ARMAGEDDON_NANOID_LEN=${ARMAGEDDON_NANOID_LEN}

ARG ARMAGEDDON_SERVER_PORT
ENV ARMAGEDDON_SERVER_PORT=${ARMAGEDDON_SERVER_PORT}

ARG ARMAGEDDON_CERT
ENV ARMAGEDDON_CERT=${ARMAGEDDON_CERT}

ARG ARMAGEDDON_PRIV_KEY
ENV ARMAGEDDON_PRIV_KEY=${ARMAGEDDON_PRIV_KEY}

ARG ARMAGEDDON_DB_PATH
ENV ARMAGEDDON_DB_PATH=${ARMAGEDDON_DB_PATH}

ARG ARMAGEDDON_SYMM_ALGORITHM
ENV ARMAGEDDON_SYMM_ALGORITHM=${ARMAGEDDON_SYMM_ALGORITHM}

ARG ARMAGEDDON_TOPIC_ID_PASS
ENV ARMAGEDDON_TOPIC_ID_PASS=${ARMAGEDDON_TOPIC_ID_PASS}

ARG ARMAGEDDON_TOPIC_ID_ALGORITHM
ENV ARMAGEDDON_TOPIC_ID_ALGORITHM=${ARMAGEDDON_TOPIC_ID_ALGORITHM}

ENV NODE_ENV=production

# Create app directory
WORKDIR /usr/src/app

RUN npm install pm2 -g

COPY ./package*.json ./
COPY ./pm2-apps.json ./
COPY ./build/ .

RUN npm config set loglevel warn \
	&& npm config set progress false \
	&& npm ci --omit=dev

EXPOSE ${ARMAGEDDON_SERVER_PORT}

CMD ["pm2-runtime", "pm2-apps.json"]
